contracts/Chainlink.sol
contracts/ZeroCollateral.sol
contracts/interfaces/ChainlinkInterface.sol

- Add `ChainlinkInterafce.sol`
- Import in `ZeroCollateralMain.sol` the `ChainlinkInterface` interface instead of `Chainlink` contract.
An advantage of this approach is that the `ZeroCollateralMain` contract does not have to store the bytecode of any called function from the `Chainlink.sol` contract.

Add Chainlink interface

---

config/networks/ganache/index.js
config/networks/ganache/maxLendingAmounts.js
config/networks/mainnet/index.js
config/networks/mainnet/maxLendingAmounts.js
config/networks/rinkeby/index.js
config/networks/rinkeby/maxLendingAmounts.js
config/networks/ropsten/index.js
config/networks/ropsten/maxLendingAmounts.js
config/networks/soliditycoverage/index.js
config/networks/soliditycoverage/maxLendingAmounts.js
config/networks/test/index.js
config/networks/test/maxLendingAmounts.js
contracts/base/EtherCollateralLoans.sol
contracts/base/LoansBase.sol
contracts/base/Settings.sol
contracts/base/TokenCollateralLoans.sol
contracts/interfaces/SettingsInterface.sol
contracts/mock/base/LoansBaseModifiersMock.sol
migrations/2_deploy.js
scripts/utils/cli-builder.js
test/base/EtherCollateralLoansCreateLoanWithTermsTest.js
test/base/LoansBaseModifiersTest.js
test/base/SettingsExceedsMaxLendingAmountTest.js
test/base/SettingsGetMaxLendingAmountTest.js
test/base/SettingsSetSettingTest.js
test/base/TokenCollateralLoansCreateLoanWithTermsTest.js
test/utils/encoders/SettingsInterfaceEncoder.js
test/utils/events.js

It includes:
- Max lending amount per asset.
- Validation in Loans.setLoanTerms.
- Configuration for networks. (1000 by default).
- Unit tests.

Add Max Lending Amount per Asset

---

contracts/base/EtherCollateralLoans.sol
contracts/base/LoanTermsConsensus.sol
contracts/base/LoansBase.sol
contracts/base/TokenCollateralLoans.sol
contracts/interfaces/LoanTermsConsensusInterface.sol
contracts/interfaces/LoansInterface.sol

It includes docs for:
- LoansInterface and Implementations (Ether and Token)
- LoansBase
- LoanTermsConsensusInterface and Implementation (LoanTermConsensus)
In each contract:
- Added docs in external / public / internal functions, constructor and events. (using @ annotations).
- The contract has a header describing the purpose and @author develop@teller.finance

[PROTOCOL-81] Adding Docs In Contracts II

---

contracts/base/LendingPool.sol
test/base/LendingPoolCreateLoanTest.js
test/base/LendingPoolDepositTest.js
test/base/LendingPoolLiquidationPaymentTest.js
test/base/LendingPoolRepayTest.js
test/base/LendingPoolWithdrawTest.js

It is:
- To verify whether the contract has enough balance or allowance and display user-friendly error messages to the final user instead, of non-readable error messages
It includes:
- "require" lending token balance validation in the tokenTransfer function in LendingPool.sol
- "require" lending token allowance validation in the tokenTransferFrom function in LendingPool.sol
- Unit test for new changes

[PROTOCOL-32] Validate Balance/Allowance Before Executing transfer/transferForm

---

package.json
yarn.lock

It is:
- Fixing the issue reported here: https://github.com/teller-protocol/teller-protocol-v1/network/alerts
It includes:
- Upgraded elliptic@^6.5.3 to address the Dependabot alert

[PROTOCOL-104] Contracts Repo: Fix Github Alert

---

contracts/base/Lenders.sol
contracts/base/LendingPool.sol
contracts/interfaces/InterestValidatorInterface.sol
contracts/interfaces/LendingPoolInterface.sol
contracts/mock/base/BaseMock.sol
migrations/2_deploy.js
migrations/utils/PoolDeployer.js
test/base/LendingPoolCreateLoanTest.js
test/base/LendingPoolDepositTest.js
test/base/LendingPoolInitializeTest.js
test/base/LendingPoolLiquidationPaymentTest.js
test/base/LendingPoolRepayTest.js
test/base/LendingPoolSetInterestValidatorTest.js
test/base/LendingPoolWithdrawInterestTest.js
test/base/LendingPoolWithdrawTest.js
test/utils/contracts.js
test/utils/encoders/InterestValidatorInterfaceEncoder.js
test/utils/events.js

It includes:
- A new InterestValidator interface to be used in the LendingPool.withdrawInterest function. By default, it will be empty. So we will not be validating the amount to withdraw. But it allows us to implement a new version in the future.
- New unit tests

[PROTOCOL-119] Adding Interest Validator

---

.github/workflows/develop-pr.yml

The Github action I'm using to get a list of changed files is not the best and spits an error (despite correctly identifying which files were changed) under some circumstances.
This fix just adds `continue-on-error: true` for this job.

Fix/ci: dont exit on changed files error

---

contracts/base/Escrow.sol
contracts/base/EscrowFactory.sol
contracts/base/LoansBase.sol
contracts/interfaces/EscrowFactoryInterface.sol
contracts/interfaces/LoansInterface.sol
contracts/mock/base/EscrowMock.sol
contracts/util/TellerCommon.sol
test/base/EscrowCallDappTest.js
test/base/EscrowFactoryAddDAppTest.js
test/base/EscrowFactoryRemoveDAppTest.js
test/base/EscrowFactoryUpdateDAppTest.js
test/base/LoansBaseIsLoanSecuredTest.js
test/utils/encoders/EscrowFactoryEncoder.js
test/utils/encoders/LoansBaseInterfaceEncoder.js
test/utils/escrow.js
test/utils/events.js

It:
* Restricts interactions for Escrows that are for an unsecured loan to Dapps that are marked as `unsecured`

[PROTOCOL-267] Limit Escrow interaction with unsecured loans.

---

contracts/base/LoanTermsConsensus.sol
contracts/interfaces/LoanTermsConsensusInterface.sol
test/base/LoanTermsConsensusProcessRequestTest.js
test/base/LoanTermsConsensusProcessResponseTest.js
test/utils/events.js

It includes:
The signer nonce value in the LoanTermsSubmitted event.

[PROTOCOL-330] Add Signer Nonce in LoanTermsSubmitted event

---

contracts/util/AddressArrayLib.sol

The AddressArrayLib functions take in `address[] storage`, meaning that it directly edits the array passed to it. This means that nothing needs to be returned from those functions as the arrays themselves have been edited and don't need to be re-assigned.

Removing AddressArrayLib return parameters

---

contracts/base/InterestConsensus.sol
test/base/EstimateGasLoanTermsConsensusProcessRequestTest.js
test/base/InterestConsensusProcessResponseTest.js

It is:
- Using the request.requestNonce parameter instead of the request.endTime parameter as the unique identifier to the _validateResponse function call in the call to the _processResponse function.

[PROTOCOL-410] [H01] Updating consensus unique identifier

---

contracts/util/PlatformSettingsLib.sol
test/base/EstimateGasLoanTermsConsensusProcessRequestTest.js
test/base/SettingsCreatePlatformSettingTest.js
test/base/SettingsUpdatePlatformSettingTest.js

It is:
- Updated error messages in the PlatformSettingsLib library to better reflect the code's behavior

[PROTOCOL-418] [L07] Misleading error messages

---

contracts/interfaces/InterestConsensusInterface.sol
contracts/interfaces/SettingsInterface.sol

Fills in the missing public getter functions from state variables.

[PROTOCOL-425]: Fix N04 - mismatch between interface and implementation

---

contracts/base/Base.sol
contracts/mock/util/NumbersListMock.sol
contracts/util/NumbersList.sol
test/util/NumbersListTest.js

- The Base contract imports the BaseUpgradeable contract which uses the AddressLib library and the SettingsInterface interface. However, the Base contract reimports this library and interface unnecessarily.
- The SettingsInterface interface imported in the Base contract is never used.
- The isFinalized method from the NumberList library is never used in the entire code base.
- The ESCROW_FACTORY_LOGIC_NAME, CHAINLINK_AGGREGATOR_LOGIC_NAME, SETTINGS_LOGIC_NAME, LOGIC_VERSIONS_REGISTRY_LOGIC_NAME, MARKETS_STATE_LOGIC_NAME, ATM_FACTORY_LOGIC_NAME, and the ATM_SETTINGS_LOGIC_NAME are never used.
NOTE: I need some help sifting through the logic names to see which should be removed.

[PROTOCOL-429] N08 - repeated or unused code

---

config/consts.js
config/networks/ganache-mainnet/platformSettings.json
config/networks/kovan/platformSettings.json
config/networks/mainnet/platformSettings.json
config/networks/rinkeby/platformSettings.json
config/networks/ropsten/platformSettings.json
config/networks/soliditycoverage/platformSettings.json
config/networks/test/platformSettings.json
contracts/base/Consensus.sol
contracts/base/InterestConsensus.sol
contracts/base/LoanTermsConsensus.sol
contracts/base/OwnerSignersRole.sol
contracts/util/SettingsConsts.sol
scripts/utils/cli/names.js
scripts/utils/cli/params.js
test-integration/initializers/1_set_settings.js
test/base/EstimateGasInterestConsensusProcessRequestTest.js
test/base/EstimateGasLoanTermsConsensusProcessRequestTest.js
test/base/InterestConsensusProcessRequestTest.js
test/base/InterestConsensusProcessResponseTest.js
test/base/LoanTermsConsensusProcessRequestTest.js
test/base/LoanTermsConsensusProcessResponseTest.js
test/base/SettingsGetAndHasPlatformSettingTest.js
test/utils/consts.js
test/utils/platformSettingsNames.js
test/utils/settings-helper.js

Fix adds a modifier to the Consensus contract requiring that the number of responses in the call is greater than or equal to number of singers - 1. Number of signers tracked when _addSigner and _removeSigner is called on OwnerSignersRole.

[PROTOCOL-409] [C01]: Interest outcome can be manipulated

---

tsconfig.json

Importing the hardhat module now automatically knows `HardhatRuntimeEnvironment` extended types.

Include utils folder in ts-config.

---

contracts/base/BaseEscrowDapp.sol
contracts/base/Settings.sol
contracts/interfaces/SettingsInterface.sol

It is: 
- Adding of event emission after changes in BaseEscrowDapp and Settings contracts to facilitate tracking and notify off-chain clients following the contracts’ activity.

[PROTOCOL-449] [M03] Lack of event emission after sensitive actions

---

contracts/util/LoanLib.sol

The audit states: 
> getCollateralNeededInTokens() in LoanLib library uses the += operator instead of a simple assignment meaning that the debt is counted twice. 
> 
> Change the operator to simply assign the result of the subtraction or document the decision of doubling the value of the loan. In either case, consider shielding the operation against underflows and overflows.
The logic is mean to add the difference of the `principalOwed` and the value of the escrow contract. Since the escrow value changes based on the tokens that it holds, the amount of required collateral can change based on this calculated difference.
A fix was made to add the `interestOwed` after the difference in value is calculated so that the interest amount is not included twice.

[PROTOCOL-442] [C01] Needed collateral for liquidation doubles when using an Escrow

---

contracts/base/Escrow.sol

It is:
- Pause escrow operations in the platform to be consistent with the current documentation

[PROTOCOL-453] [M08] Borrower can use DApps during a paused scenario

---

contracts/base/LendingPool.sol

* Burns the TToken balances for the current lenders
* Resets the stored underlying balance with the original supplied amount
* Mints a 1:1 ratio of TTokens for the lenders balance and the remaining balance is given to the Teller deployer account.

Fix for lender balance and exchange rate.

---

contracts/base/MarketFactory.sol
contracts/base/escrow/Escrow.sol
contracts/base/lending-pool/LendingPool.sol
contracts/base/loans/LoanManager.sol
contracts/base/upgradeable/DynamicUpgradeable.sol
test/integration/loans.test.ts

It only updates `DynamicProxy` cached address via a modifier. 
Each function in a contract that extends the `DynamicUpgradeable` contract that is `external` and **NOT** `view` should use this modifier as the very _**FIRST**_ modifer so that if the logic needs to be updated, other modifiers get the applied update.

Fix Strict Dynamic Cache Update

---

contracts/nft/IStakeableNFT.sol
contracts/nft/TellerNFTDictionary.sol
deploy/nft.ts
tasks/fork.ts
tasks/nft/add-nft-tiers.ts
test/unit/nft-dictionary.test.ts

Adding NFT dictionary contract + deploy scripts which will add auxiliary metadata for the TellerNFTV1 to make accessing this data in the EVM more efficient.
Still need to:
-Write deploy script which will add + append 'TierIndex' data for each tokenId.   
-add code to the NFTDistributor which will append TierIndex data to the NFTDictionary when an NFT is minted.

Nftdictionary

---

contracts/nft/distributor/entry/initialize.sol
deploy/nft.ts

resolves bug related to NFTDictionary initialization on a chain that does not yet have the Distributor deployed to it [such as polygon]

resolves bug related to NFTDictionary initialization  

---

hardhat.config.ts

Sets the block number to fork mainnet to after the latest deployment

Update Mainnet Forking Block Number 

---

deploy/nft.ts
utils/deploy-helpers.ts

An upgrade was made to the `hardhat-deploy` package that broke the deploy script for proxy contracts.

Fix Deploy NFT Script

---

package.json

Files are not being linted and type checked before being committed. This update runs `yarn build && eslint --fix` on staged files before the commit is made.

Run yarn build && eslint for staged files on commit

---

package.json

Prettier was only running on Solidity files. Now `prettier` and `eslint` will run on TypeScript and JavaScript files.

Run prettier on ts and js file during precommit

---

hardhat.config.ts

The block used to fork a network locally, for tests and other operations, was previously hard coded in the `hardhat.config.ts` file which made it cumbersome to manually update this value after a new deployment. 
We are already saving a file in the `deployments` directory for each network called `.latestDeploymentBlock` that is updated during the deployment process. This value is now being loaded during these operations.

Fork Network Using Latest Deployment Block

---

contracts/lending/ttoken/TToken_V1.sol

added a check to ensure the calculated amounts to mint, redeem and burn are non-zero

[PROTOCOL-634] [M01] Exchange rate rounding

---

contracts/lending/ttoken/ITToken.sol
contracts/lending/ttoken/TToken_V1.sol
contracts/lending/ttoken/strategies/compound/TTokenCompoundStrategy_1.sol

Removed misleading comments
```
In TToken_V1.sol:
- Line 46 implies a valid condition is if the lending pool “has the CONTROLLER role”. This should say “the message sender has the CONTROLLER role”.
- Line 158 suggests debtRatioFor returns a boolean, but it just returns the ratio without indicating whether it is valid. This mistake is repeated in ITToken.
- Line 443 states the message sender “must have ADMIN role”. There is no such restriction.
- Line 335 states “Sets a new strategy to use for balancing funds”, however the setStrategy function can also be used to update the parameters of the current strategy instead of replacing it with a new one.
In TTokenCompoundStrategy_1:
- Line 106 says compoundBalance_ is the total stored balance, but it is the amount of underlying value stored in …
```

[PROTOCOL-645] [N01] Misleading comments

---

contracts/lending/ttoken/ITToken.sol
contracts/lending/ttoken/TToken_V1.sol

fixed all typographical errors stated
```
Line 70 of TToken_V1.sol and line 38 of ITToken.sol say “assets” instead of “asset”.
Line 71 of TToken_V1.sol has been truncated.
Line 91 of TToken_V1.sol and line 54 of ITToken.sol say “of” instead of “off” (or “on”).
Line 117 of TToken_V1.sol says “markets” instead of “market”.
Line 251 of TToken_V1.sol and line 132 of ITToken.sol say “token underlying” instead of “tokens for underlying”.
Line 427 of TToken_V1.sol says “retrives” instead of “retrieves”.
```

 [PROTOCOL-648] [N04] Typographical errors

---

contracts/lending/ttoken/ITToken.sol
contracts/lending/ttoken/TToken_V1.sol
contracts/lending/ttoken/strategies/ITTokenStrategy.sol
contracts/lending/ttoken/strategies/compound/TTokenCompoundStrategy_1.sol

Dup of #423 using correct branch naming structure 
> Adding event emissions to the following relevant events:
> - The restrict function from the TToken_V1 contract.
> - The repayLoan function from the TToken_V1 contract when a loan has been repaid.
> - The fundLoan function from the TToken_V1 contract when a loan has been taken out.
> - The setStrategy function from the TToken_V1 contract.
> - The init function from the TTokenCompoundStrategy_1 contract when setting new parameters for the strategy.

[PROTOCOL-636] [M03] Lack of event emission after sensitive actions

---

contracts/lending/ttoken/TToken_V1.sol
contracts/lending/ttoken/strategies/compound/TTokenCompoundStrategy_1.sol
contracts/lending/ttoken/token-storage.sol

Duplicate of #425 using correct branch naming structure
> Adding missing docstrings to the following:
> - tToken exchangeRate()
> - tToken mint()
> - Store struct of tToken storage.sol
> - TTokenCompoundStrategy init()

[PROTOCOL-637] [L01] Missing docstrings

---

contracts/lending/ttoken/strategies/compound/TTokenCompoundStrategy_1.sol

Duplicate of #424 using correct branch naming structure
> Adding reversion guards to tToken Compound strategy whenever calls to cToken contracts are unsuccessful

[PROTOCOL-635] [M02] Discarding Compound Errors

---

contracts/lending/ttoken/TToken_V1.sol

Duplicate of #426 using correct branch naming structure
> Adding reentrancy guards to tToken operations:
> - mint()
> - redeem()
> - redeemUnderlying()

[PROTOCOL-640] [L03] ERC777 Reentrancy

---

deploy/nft.ts

Updating NFT deploy script to readd the deployment of NFT V1 on L1 (if not already deployed)
(included in PR #464 )
this is useful for when we do fresh deployments on testnets

NFT deploy script update

---

hardhat.config.ts
utils/hre-extensions.ts

* Extends the `HRE` object to set the Tenderly project name based on the network being used by Hardhat

Set Tenderly project config based on network being used

---

contracts/escrow/dapps/CompoundClaimComp.sol
contracts/market/CreateLoanWithNFTFacet.sol
contracts/market/mainnet/MainnetCreateLoanWithNFTFacet.sol
test/helpers/loans.ts
test/integration/loans.test.ts

Given that the user has a combination of V1 and V2 tokens, we need to combine both NFT ID types to take out a loan. It doesn't make sense for a user to discriminate between a V1 and a V2 token when they are just trying to take out a loan.
An extra version # has been added in the `CreateLoanWithNFTFacet.sol` and the `MainnetCreateLoanWithNFTFacet.sol`. A new test has also been added in the `loans.test.ts` and the helper function for `takeOutLoanWithNFTs` is updated with the new `case: 3`

[PROTOCOL-954] Take Out Loan V3
