- contracts/Chainlink.sol
- contracts/ZeroCollateral.sol
- contracts/interfaces/AggregatorInterface.sol
- contracts/utils/Context.sol
- contracts/utils/Ownable.sol
> add chainlink data feed contract

- .solhint.json
- contracts/ZeroCollateral.sol
- Added Solhint to the repo
- Linted ZeroCollateral.sol
> Solidity Linting

- .env.template
- .solcover.js
- config/env/EnvConfig.js
- config/env/EnvValue.js
- config/env/index.js
- contracts/Migrations.sol
- contracts/mock/token/SimpleToken.sol
- contracts/mock/util/Mock.sol
- migrations/2_deploy.js
- package.json
- test/ERC20TransferTest.js
- test/utils/consts.js
- test/utils/events.js
- truffle-config.js
- yarn.lock
It includes:
- Truffle configuration to deploy smart contracts.
- Unit tests support.
- Ether gas reporter for tests.
- Env variable support (including an env variable template file).
- Code coverage support.
Unit tests and Ether Gas Report
Code Coverage Report Sample
> Adding support for testing

- .circleci/config.yml
- contracts/ZeroCollateral.sol
- test/ZeroCollateralDepositCollateralBorrowerTest.js
- test/utils/events.js
It contains:
- Fixing compilation errors in master.
- Modifying depositCollateralBorrower to accept ETH.
- Adding unit tests for depositCollateralBorrower.
- Adding CircleCI configuration.
> Modifying depositCollateralBorrower to accept ETH

- config/env/EnvConfig.js
- contracts/Migrations.sol
- contracts/ZDai.sol
- contracts/ZeroCollateral.sol
- contracts/mock/base/ZeroCollateralMock.sol
- test/ZeroCollateralDepositCollateralBorrowerTest.js
- test/ZeroCollateralMockTest.js
It contains:
- New fields in Borrow struct.
- Mock contract and function to set test data.
> Create a mock contract to set mocked borrow data

- contracts/interfaces/DAIPoolInterface.sol
- contracts/interfaces/LenderInfoInterface.sol
- contracts/interfaces/LoanInfoInterface.sol
- contracts/interfaces/ZDAIInterface.sol
Adding new interfaces (drafts) for the initial design.
> Adding interfaces for modules.

- .prettierrc
- .solhint.json
- contracts/base/LenderInfo.sol
- contracts/interfaces/DAIPoolInterface.sol
- contracts/interfaces/LenderInfoInterface.sol
- contracts/interfaces/LoanInfoInterface.sol
- contracts/interfaces/PairAggregatorInterface.sol
- contracts/interfaces/ZDAIInterface.sol
- contracts/interfaces/ZeroCollateralInterface.sol
- contracts/mock/base/LenderInfoMock.sol
- contracts/mock/base/LenderInfoModifiersMock.sol
- contracts/mock/token/SimpleToken.sol
- contracts/util/AddressLib.sol
- contracts/util/ZeroCollateralCommon.sol
- package.json
- test/base/LenderInfoCalculateNewAccruedInterestForTest.js
- test/base/LenderInfoConstructorTest.js
- test/base/LenderInfoModifiersTest.js
- test/base/LenderInfoUpdateAccruedInterestForTest.js
- test/base/LenderInfoWithdrawInterestTest.js
- test/base/LenderInfoZDaiBurntTest.js
- test/base/LenderInfoZDaiMintedTest.js
- test/base/LenderInfoZDaiTransferTest.js
- test/utils/consts.js
- test/utils/contracts.js
- test/utils/encoders/ERC20InterfaceEncoder.js
- test/utils/events.js
- truffle-config.js
- yarn.lock
It contains:
- Most of the functions for the LenderInfo contract.
- Unit tests for all implemented functions (code coverage ~=95%) in LenderInfo contract.
- Prettier Solidity formatter plugin.
- Husky hooks:
- Pre-commit: Formatting smart contracts.
- Pre-push: Running unit tests.
The interest earned calculation process/formula is being analyzed by the team. So, it eventually will be changed in a new PR once it is defined.
I have used the Slither tool to analyze the LenderInfo.sol contract. It got only one issue related to the Solidity version. So, there weren't low/medium/high priority issues.
> Implementing LenderInfo contract

- contracts/base/Loans.sol
- contracts/interfaces/DAIPoolInterface.sol
- contracts/interfaces/LoansInterface.sol
- contracts/mock/base/LoansMock.sol
- test/base/LoansTakeOutLoanTest.js
- test/utils/consts.js
- test/utils/events.js
- test/utils/hashes.js
- truffle-config.js
It contains:
- Fix to update loan id when a user takes out a loan.
- Unit tests to assert loan id is updated properly.
> Fix - Loans.takeOutLoan: Update loan id

- contracts/mock/util/NumbersListMock.sol
- contracts/util/NumbersList.sol
- test/util/NumbersListTest.js
- truffle-config.js
It contains:
- New numbers library to calculate min/max/sum/length.
- Unit tests.
> Adding Numbers library

- contracts/base/Settings.sol
- test/base/SettingsSetSettingTest.js
- test/utils/consts.js
It includes:
- New unit tests to increase code coverage in the Settings contract.
> Settings: new unit tests

- .env.template
- config/env/EnvConfig.js
- truffle-config.js
It contains:
- New env variable to make the Ganache configuration more flexible.
It allows us to use docker to inject env variable and use it in the full integration tests.
> Ganache configuration: new env variables

- .dockerignore
- .gitignore
- docker/Dockerfile
New: Added .dockerignore file to send the right context on docker buildUpdate: Added .idea to .gitignore
New: Added a Dockerfile for image fabrxorg/teller-protocol-v1
This PR is part of a group of PR related to:
https://github.com/Zero-Collateral/builder/pull/7
> New: Added a Dockerfile recipe to be able to launch integration tests via docker 

- .dockerignore
- .gitignore
- config/networks/ganache/chainlink.js
- config/networks/ropsten/chainlink.js
- config/networks/soliditycoverage/chainlink.js
- config/networks/soliditycoverage/index.js
- config/networks/test/chainlink.js
- contracts/base/LoansBase.sol
- contracts/interfaces/EtherLoansInterface.sol
- contracts/interfaces/TokenLoansInterface.sol
- contracts/mock/base/EtherLoansMock.sol
- contracts/mock/base/TokenLoansMock.sol
- contracts/mock/providers/chainlink/InverseChainlinkPairAggregatorMock.sol
- contracts/mock/providers/chainlink/PairAggregatorMock.sol
- contracts/providers/chainlink/ChainlinkPairAggregator.sol
- contracts/providers/chainlink/InverseChainlinkPairAggregator.sol
- docker/Dockerfile
- migrations/2_deploy.js
- migrations/3_deploy_mocks.js
- migrations/utils/PoolDeployer.js
- scripts/oracle/getPrices_chainlink.js
- test/base/LoansBaseGetCollateralInfoTest.js
- test/providers/chainlink/ChainlinkPairAggregatorConstructorTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetLatestAnswerTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetLatestRoundTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetLatestTimestampTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetPreviousAnswerTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetPreviousTimestampTest.js
- test/providers/chainlink/InverseChainlinkPairAggregatorGetLatestAnswerTest.js
- test/providers/chainlink/InverseChainlinkPairAggregatorGetPreviousAnswerTest.js
It contains:
- A new inverse price implementation.
- Configuration for token and response decimals (based on Chainlink team).
- New getCollateralInfo view function.
- New unit tests to verify collateral using new oracle impl.
> Fix Oracle Issues

- contracts/base/Base.sol
- contracts/base/Consensus.sol
- contracts/base/EtherCollateralLoans.sol
- contracts/base/InterestConsensus.sol
- contracts/base/Lenders.sol
- contracts/base/LoanTermsConsensus.sol
- contracts/base/LoansBase.sol
- contracts/base/TokenCollateralLoans.sol
- contracts/interfaces/LoansInterface.sol
- contracts/mock/base/InterestConsensusMock.sol
- contracts/mock/base/LoanTermsConsensusMock.sol
- contracts/mock/base/LoansBaseMock.sol
- contracts/mock/util/NumbersListMock.sol
- contracts/util/NumbersList.sol
- scripts/loans/createLoanWithTerms.js
- test-integration/deposit-collateral/1_loans_deposit_link_collateral.js
- test-integration/liquidate-loan/1_liquidate_eth_by_collateral.js
- test-integration/liquidate-loan/2_liquidate_eth_by_endDate.js
- test/base/BaseInitializeTest.js
- test/base/ConsensusModifiersTest.js
- test/base/EtherCollateralLoansCreateLoanWithTermsTest.js
- test/base/EtherCollateralLoansRepayTest.js
- test/base/LendersModifiersTest.js
- test/base/LendersWithdrawInterestTest.js
- test/base/LendingPoolWithdrawInterestTest.js
- test/base/LoanTermsConsensusHashesTest.js
- test/base/LoansBaseGetCollateralInfoTest.js
- test/base/TokenCollateralLoansCreateLoanWithTermsTest.js
- test/util/NumbersListTest.js
It includes fixes for the "Adherence to Best Practices" issues found in the audit process.
> Audit: Best practices Fixes

- contracts/base/Base.sol
- contracts/base/Consensus.sol
- contracts/base/Lenders.sol
- contracts/base/LendingPool.sol
- contracts/base/LoansBase.sol
- contracts/base/Settings.sol
- contracts/base/TokenCollateralLoans.sol
- contracts/base/ZToken.sol
- contracts/base/ZUSDC.sol
- contracts/interfaces/ZTokenInterface.sol
- contracts/mock/base/LendersMock.sol
- contracts/mock/base/TokenCollateralLoansMock.sol
- contracts/mock/token/ERC20Mock.sol
- contracts/providers/chainlink/ChainlinkPairAggregator.sol
- contracts/providers/openzeppelin/SignedSafeMath.sol
- contracts/util/NumbersList.sol
- package.json
- scripts/loans/repay.js
- test/base/EstimateGasInterestConsensusProcessRequestTest.js
- test/base/EstimateGasLoanTermsConsensusProcessRequestTest.js
- test/base/LendersWithdrawInterestTest.js
- test/base/LendingPoolWithdrawInterestTest.js
- test/base/LoansBaseGetCollateralInfoTest.js
- test/base/SettingsSetSettingTest.js
- truffle-config.js
- yarn.lock
It includes fixes for the "Low and info" issues found in the audit process
> Fix Low and Info Issues

- contracts/base/Consensus.sol
- contracts/base/InterestConsensus.sol
- contracts/base/LoanTermsConsensus.sol
- contracts/mock/base/InterestConsensusMock.sol
- contracts/mock/base/LoanTermsConsensusMock.sol
- test/base/ConsensusSignatureValidTest.js
- test/base/EstimateGasInterestConsensusProcessRequestTest.js
- test/base/EstimateGasLoanTermsConsensusProcessRequestTest.js
- test/base/InterestConsensusHashesTest.js
- test/base/InterestConsensusProcessRequestTest.js
- test/base/InterestConsensusProcessResponseTest.js
- test/base/LoanTermsConsensusHashesTest.js
- test/base/LoanTermsConsensusProcessRequestTest.js
- test/base/LoanTermsConsensusProcessResponseTest.js
- test/utils/chains.js
- test/utils/hashes.js
It includes:
- Chain id in the hashes to avoid attacks across chains.
- Changes in unit tests.
> Add chain id to hashes

- contracts/interfaces/PairAggregatorInterface.sol
- contracts/providers/chainlink/ChainlinkPairAggregator.sol
- contracts/providers/chainlink/InverseChainlinkPairAggregator.sol
It includes docs
- PairAggregatorInterface
- ChainlinkPairAggregator
-  InverseChainlinkPairAggregator
> Adding Docs in Contracts V

- contracts/base/Base.sol
- contracts/base/Consensus.sol
- contracts/base/Initializable.sol
- contracts/base/Settings.sol
- contracts/base/ZDai.sol
- contracts/base/ZToken.sol
- contracts/base/ZUSDC.sol
- contracts/interfaces/SettingsInterface.sol
- contracts/interfaces/ZTokenInterface.sol
- contracts/util/AddressLib.sol
- contracts/util/NumbersList.sol
- contracts/util/ZeroCollateralCommon.sol
It includes docs:
- Settings
- SettingsInterface
- Consensus
- Base
- Initializable
> Adding docs in contracts III

- contracts/base/LendingPool.sol
- test/base/LendingPoolInitializeTest.js
- test/base/LendingPoolLiquidationPaymentTest.js
- test/base/LendingPoolRepayTest.js
- test/base/LendingPoolWithdrawInterestTest.js
- test/base/LendingPoolWithdrawTest.js
- test/base/LoansBaseLendingTokenTest.js
- test/base/TokenCollateralLoansDepositCollateralTest.js
It includes:
- Support lending tokens without a cToken (Compound tokens).
> [PROTOCOL-91] Support Assets without a cToken

- .env.template
- .gitignore
- config/env/EnvConfig.js
- contracts/base/EtherCollateralLoans.sol
- contracts/base/LoansBase.sol
- contracts/base/Settings.sol
- contracts/base/TokenCollateralLoans.sol
- contracts/interfaces/SettingsInterface.sol
- contracts/mock/base/LoansBaseModifiersMock.sol
- migrations/2_deploy.js
- scripts/settings/setSettingsValue.js
- test/base/BaseWhenNotPausedTest.js
- test/base/BaseWhenPausedTest.js
- test/base/EstimateGasInterestConsensusProcessRequestTest.js
- test/base/EstimateGasLoanTermsConsensusProcessRequestTest.js
- test/base/EtherCollateralLoansCreateLoanWithTermsTest.js
- test/base/EtherCollateralLoansGetBorrowerLoansTest.js
- test/base/EtherCollateralLoansTakeOutLoanTest.js
- test/base/InterestConsensusProcessRequestTest.js
- test/base/InterestConsensusProcessResponseTest.js
- test/base/LoanTermsConsensusProcessRequestTest.js
- test/base/LoanTermsConsensusProcessResponseTest.js
- test/base/LoansBaseModifiersTest.js
- test/base/SettingsConstructorTest.js
- test/base/SettingsPauseLendingPoolTest.js
- test/base/SettingsSetSettingTest.js
- test/base/SettingsUnpauseLendingPoolTest.js
- test/base/TokenCollateralLoansCreateLoanWithTermsTest.js
- test/utils/encoders/SettingsInterfaceEncoder.js
- test/utils/settings-map.js
It includes:
- New setting.
- Adding validation in XXXCollateralLoans.createLoanWithTerms function.
- Changing current unit tests.
> [PROTOCOL-76] Adding New 'MaxLoanDuration' Setting

- .env.template
- config/env/EnvConfig.js
- contracts/base/Settings.sol
- contracts/interfaces/SettingsInterface.sol
- migrations/2_deploy.js
- test/base/BaseWhenNotPausedTest.js
- test/base/BaseWhenPausedTest.js
- test/base/EstimateGasInterestConsensusProcessRequestTest.js
- test/base/EstimateGasLoanTermsConsensusProcessRequestTest.js
- test/base/EtherCollateralLoansCreateLoanWithTermsTest.js
- test/base/EtherCollateralLoansGetBorrowerLoansTest.js
- test/base/EtherCollateralLoansTakeOutLoanTest.js
- test/base/InterestConsensusProcessRequestTest.js
- test/base/InterestConsensusProcessResponseTest.js
- test/base/LoanTermsConsensusProcessRequestTest.js
- test/base/LoanTermsConsensusProcessResponseTest.js
- test/base/SettingsConstructorTest.js
- test/base/SettingsCreateAssetSettingsTest.js
- test/base/SettingsPauseLendingPoolTest.js
- test/base/SettingsRemoveAssetSettingsTest.js
- test/base/SettingsSetSettingTest.js
- test/base/SettingsUnpauseLendingPoolTest.js
- test/base/SettingsUpdateAssetSettingsTest.js
- test/base/TokenCollateralLoansCreateLoanWithTermsTest.js
- test/utils/settings-map.js
It includes:
- Changes in the Settings contract.
- Changes in unit tests.
> [PROTOCOL-98] Adding Starting Block Number Setting

- config/networks/rinkeby/index.js
- config/networks/soliditycoverage/index.js
- config/networks/test/index.js
- contracts/base/Base.sol
- contracts/base/LoansBase.sol
- contracts/base/Settings.sol
- contracts/interfaces/LoansInterface.sol
- contracts/interfaces/SettingsInterface.sol
- contracts/mock/base/BaseMock.sol
- test/base/BaseWhenAllowedTest.js
- test/base/LoansBaseSetPriceOracleTest.js
- test/utils/encoders/SettingsInterfaceEncoder.js
- test/utils/events.js
- truffle-config.js
It includes:
- A setter function to update the oracle reference.
> [PROTOCOL-22] Add Setter Function For Oracle Price Reference

- .github/workflows/run-ci.yml
Removing the execution of unit tests on CI (only code coverage -it runs the unit tests-).
> Removing Unit Tests Execution (only code coverage).

- contracts/atm/ATMGovernanceFactoryInterface.sol
- contracts/base/ATM/ATMToken.sol
- contracts/base/ATM/ATMTokenInterface.sol
- contracts/mock/base/BaseMock.sol
- contracts/settings/ATMSettings.sol
- contracts/settings/ATMSettingsInterface.sol
- test/base/MarketsStateGetSupplyToDebtForTest.js
- test/settings/ATMSettingsConstructorTest.js
- test/settings/ATMSettingsIsATMPausedTest.js
- test/settings/ATMSettingsPauseATMTest.js
- test/settings/ATMSettingsRemoveATMToMarketTest.js
- test/settings/ATMSettingsSetATMToMarketTest.js
- test/settings/ATMSettingsUnpauseATMTest.js
- test/settings/ATMSettingsUpdateATMToMarketTest.js
- test/utils/encoders/ATMGovernanceFactoryInterfaceEncoder.js
- test/utils/encoders/SettingsInterfaceEncoder.js
- test/utils/events.js
It includes:
Note: As I needed the ATMGovernanceFactoryInterface, I copied/pasted from another PR.
- Ability to pause an ATM.
- Configuration in the ATM settings contract.
> [PROTOCOL-135, PROTOCOL-141] Create ATM Settings Contract

- config/networks/ganache/platformSettings.js
- config/networks/mainnet/platformSettings.js
- config/networks/rinkeby/platformSettings.js
- config/networks/ropsten/platformSettings.js
- config/networks/soliditycoverage/platformSettings.js
- config/networks/test/platformSettings.js
- contracts/base/LoanTermsConsensus.sol
- contracts/mock/base/BaseMock.sol
- contracts/mock/base/LoanTermsConsensusMock.sol
- contracts/util/SettingsConsts.sol
- test/base/EstimateGasLoanTermsConsensusProcessRequestTest.js
- test/base/LoanTermsConsensusProcessRequestTest.js
- test/base/LoanTermsConsensusRequireRequestLoanTermsRateLimitTest.js
- test/utils/platformSettingsNames.js
It includes:
- New setting.
- Validation of the rate limit when a borrower tries to request loan terms.
> [PROTOCOL-164] Add Request Loan Terms Rate Limit Validation

- contracts/atm/ATMToken.sol
It fixes some compilation warnings in the ATM Token contract.
> Fixes: ATM Token Compilation Issues

- config/networks/mainnet/atms.js
- config/networks/mainnet/chainlink.js
- config/networks/mainnet/compound.js
- config/networks/mainnet/dao.js
- config/networks/mainnet/index.js
- config/networks/mainnet/platformSettings.js
- config/networks/mainnet/signers.js
- config/networks/rinkeby/index.js
- config/networks/rinkeby/platformSettings.js
- config/networks/ropsten/dao.js
- config/networks/ropsten/index.js
- config/networks/ropsten/platformSettings.js
- contracts/base/TDAI.sol
- contracts/base/TUSDC.sol
- test/base/EtherCollateralLoansDepositCollateralTest.js
- test/base/EtherCollateralLoansTakeOutLoanTest.js
- test/base/EtherCollateralLoansWithdrawCollateralTest.js
- truffle-config.js
It includes:
- Truffle configuration.
- Platform configuration.
> [PROTOCOL-174] Add Mainnet Config

- contracts/atm/ATMFactory.sol
- contracts/atm/IATMFactory.sol
- test/ATM/ATMFactoryInitializeTest.js
- test/ATM/ATMFactorySetATMSettingsTest.js
- test/ATM/ATMFactorySetSettingsTest.js
- test/atm/ATMGovernanceUpdateAssetMarketSettingTest.js
- test/utils/events.js
It is:
- Increased code coverage and docs
It includes:
- Additional ATMFactory tests
- Docs for ATMFactory implementation and interface
> [PROTOCOL-182] ATMGovernance: Increase Code Coverage

- test/base/UpgradeableProxyUpgradeToTest.js
- test/utils/events.js
Add to the existing test that an `Upgraded` event was emitted.
> [PROTOCOL-176] Emit Event On Contract Upgrade

- contracts/providers/chainlink/ChainlinkPairAggregator.sol
- test/providers/chainlink/ChainlinkPairAggregatorGetLatestAnswerTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetLatestRoundTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetLatestTimestampTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetPreviousAnswerTest.js
- test/providers/chainlink/ChainlinkPairAggregatorGetPreviousTimestampTest.js
- test/providers/chainlink/ChainlinkPairAggregatorInitializeTest.js
- test/providers/chainlink/InverseChainlinkPairAggregatorGetLatestAnswerTest.js
- test/providers/chainlink/InverseChainlinkPairAggregatorGetPreviousAnswerTest.js
It is:
- Fixes for the escrow chainlink tests
It includes:
- Test fixes
- Renamed ChainlinkPairAggregatorContructorTest.js to ChainlinkPairAggregatorInitializeTest.js
> Fixing escrow chainlink tests

- contracts/base/UpgradeableProxy.sol
- test/base/UpgradeableProxySettingsCreatePlatformSettingTest.js
- test/base/UpgradeableProxyUpgradeToTest.js
Test fixes for improving contract versions
> Test fixes 3

- config/networks/ganache/atms.js
- config/networks/mainnet/atms.js
- config/networks/rinkeby/atms.js
- config/networks/ropsten/atms.js
- config/networks/soliditycoverage/atms.js
- config/networks/test/atms.js
- contracts/base/OwnerSignersRole.sol
- contracts/providers/chainlink/ChainlinkPairAggregatorRegistry.sol
- contracts/providers/chainlink/IChainlinkPairAggregatorRegistry.sol
- migrations/utils/init_settings/initPairAggregators.js
- migrations/utils/init_settings/initSignerAddresses.js
- package.json
It includes:
- New function to add multiple signers.
- New function to add multiple pair aggregators.
> Add multiple signers and pair aggregators

- package.json
- yarn.lock
It includes fixing for dependencies.
> Fixing dependencies issues.

- contracts/settings/ATMSettings.sol
- test/settings/ATMSettingsSetATMToMarketTest.js
It includes:
- Fixes in ATMSettings (best practices).
> [PROTOCOL-252] ATMSettings: Fixing Best Practices

- contracts/base/BaseEscrowDapp.sol
- contracts/base/Escrow.sol
- contracts/base/escrow/dapps/Compound.sol
- contracts/base/escrow/dapps/ICompound.sol
- contracts/base/escrow/dapps/IUniswap.sol
- contracts/base/escrow/dapps/Uniswap.sol
- contracts/mock/base/escrow/dapps/CompoundMock.sol
- contracts/mock/base/escrow/dapps/DappMock.sol
- contracts/mock/base/escrow/dapps/UniswapMock.sol
- test/base/EscrowCallDappTest.js
- test/base/escrow/dapps/CompoundLendTest.js
- test/base/escrow/dapps/CompoundRedeemTest.js
- test/base/escrow/dapps/UniswapSwapTest.js
It fixes access to the Escrow Dapp functions.
* Gives access to the `owner` of the Escrow contract to the Dapp contracts.
* Restricts access to call them to only the owner of the Escrow.
> [PROTOCOL-241] [QSP-1] Dapp Function Visibility

- .github/workflows/develop-pr.yml
- contracts/base/BaseUpgradeable.sol
- contracts/base/InitializeableDynamicProxy.sol
- contracts/mock/base/BaseUpgradeableMock.sol
- contracts/mock/base/InitializeableDynamicProxyMock.sol
- contracts/settings/ATMSettings.sol
- test/base/BaseUpgradeableOnlyPauserTest.js
- test/base/BaseUpgradeableSetLogicNameTest.js
- test/base/BaseUpgradeableSetSettingsTest.js
- test/base/InitializeableDynamicProxyImplementationTest.js
- test/base/InitializeableDynamicProxyInitializeProxyTest.js
- test/settings/ATMSettingsSetATMToMarketTest.js
It includes:
- New unit tests to increase code coverage in contracts: BaseUpgradeable and InitializeableDynamicProxy.
- Docs in contracts BaseUpgradeable and InitializeableDynamicProxy.
> [PROTOCOL-254][CodeCoverage] Increase Coverage BaseUpgradeable and InitializeableDynamicProxy

- contracts/atm/TLRToken.sol
It includes:
- Modifiers: whenNotPaused() and isInitialized() in TLRToken.transfer function.
> [PROTOCOL-277] Add modifiers to TLRToken

- contracts/base/Escrow.sol
- contracts/base/EscrowFactory.sol
- contracts/base/LoansBase.sol
- contracts/mock/base/InitializeableDynamicProxyMock.sol
- contracts/mock/token/ERC20Mock.sol
- test/base/InitializeableDynamicProxyImplementationTest.js
it includes:
- Changes to cover a pending escenario.
> Increase InitializeableDynamicProxy Code Coverage

- package.json
- yarn.lock
It includes:
- Changes in the package.json to fix the alert issue.
> Fixing dependency alert.

- contracts/base/Escrow.sol
- contracts/base/LoansBase.sol
- contracts/mock/base/LoansBaseMock.sol
- test/base/EscrowClaimTokensTest.js
- test/base/EstimateGasEscrowCalculateTotalValueTest.js
- test/base/EstimateGasEscrowClaimTokensTest.js
- test/base/EtherCollateralLoansRepayTest.js
- test/utils/loans.js
It:
* Restricts borrower from claiming tokens if loan liquidated.
> Fix Escrow.claimTokens

- contracts/base/Escrow.sol
- test/base/EscrowRepayTest.js
- test/utils/encoders/LoansBaseInterfaceEncoder.js
It:
* Sets the allowance on the Lending Pool instead of the Loans contract
* Only takes the necessary amount of funds to repay the loan if Escrow balance does not cover the amount
> Fix Escrow Repay

- contracts/base/TTokenRegistry.sol
- contracts/interfaces/TTokenRegistryInterface.sol
- migrations/2_deploy.js
- test/base/TTokenRegistryInitializeTest.js
- test/base/TTokenRegistryIsTTokenTest.js
- test/base/TTokenRegistryRegisterTTokenTest.js
- test/utils/events.js
- test/utils/logicNames.js
It is:
- TTokenRegistry for ttokens created
It includes: 
- TTokenRegistry contract with registerTToken() and isTToken() methods 
- TTokenRegistryInterface
- Associated tests
> [PROTOCOL-293] TToken registry

- scripts/utils/GetContracts.js
- test-integration/utils/actions/atmGovernance.js
It is:
- ATM governance actions for integration tests
> [PROTOCOL-309] - Integration Tests - ATM Governance - Create Generic Functions (Actions)

- contracts/base/LoansBase.sol
- test-integration/scenarios/loans/1_takeout_loan_and_2_repays_full_successfully.js
- test-integration/scenarios/loans/4_takeout_loan_and_not_withdraw_too_much_collateral.js
- test-integration/scenarios/loans/5_takeout_loan_invalid_supply_to_debt_ratio.js
- test-integration/scenarios/loans/6_takeout_loan_invalid_too_short_time_request_loan_terms.js
- test-integration/scenarios/loans/index.js
- test-integration/utils/actions/index.js
- test-integration/utils/actions/loans.js
- test-integration/utils/actions/settings.js
- test/base/EtherCollateralLoansWithdrawCollateralTest.js
- test/base/TokenCollateralLoansWithdrawCollateralTest.js
It includes:
- 3 new scenarios (integration tests) for the category loans.
New scenarios:
4: Error taking out a loan and take out too much collateral
5: Error taking out a loan with invalid supply to debt ratio
6: Error taking out a loan in a too short amount of time (from request loan terms)
> [PROTOCOL-297] Loans: Adding 3 new Scenarios (4-6)

- migrations/3_deploy.js
It includes:
- Liquidity mining deployment fix.
> [PROTOCOL-370] Fixing LiquidityMining deploy

- contracts/base/Settings.sol
- contracts/interfaces/SettingsInterface.sol
- migrations/3_deploy.js
- test/base/EscrowFactoryCreateEscrowTest.js
- test/base/TTokenRegistryInitializeTest.js
- test/base/TTokenRegistryIsTTokenTest.js
- test/base/TTokenRegistryRegisterTTokenTest.js
- test/utils/settings-helper.js
It includes:
- New state variable in Settings contract.
- Settings contract initialize() function new parameter.
- Unit tests using Settings modified.
> [PROTOCOL-375] Feature/get CETH address dynamically

- contracts/providers/chainlink/ChainlinkAggregator.sol
- test/providers/chainlink/ChainlinkAggregatorLatestAnswerForTest.js
- test/providers/chainlink/ChainlinkAggregatorValueForTest.js
- test/utils/encoders/AggregatorV2V3InterfaceEncoder.js
It:
* Uses the decimals defined on the Chainlink AggregatorV2V3 contract to know what the response decimals are and scales the response price when calculating the value of another token amount.
> [PROTOCOL-376] Use AggregatorV2V3 decimals

- contracts/base/BaseEscrowDapp.sol
- contracts/base/LoansBase.sol
- contracts/util/AddressArrayLib.sol
- contracts/util/MarketStateLib.sol
- contracts/util/SettingsConsts.sol
It is updated natspec for:
- BaseEscrowDapp
- TellerCommon
- LoansBase
- AddressLib
- SettingsConsts
> [PROTOCOL-389] Update Natspec II

- contracts/base/LendingPool.sol
- test/base/LendingPoolLiquidationPaymentTest.js
It includes:
- Increase repayment amount on liquidation.
- Fixes on unit tests.
> [PROTOCOL-383] Updating Market State on Liquidation

- contracts/base/MarketsState.sol
- contracts/interfaces/MarketsStateInterface.sol
It includes:
- A global market state.
- New function in MarketsStateInterface.
> [PROTOCOL-345] Adding Global Market State

- contracts/base/TDAI.sol
- contracts/base/TToken.sol
- contracts/base/TUSDC.sol
- migrations/3_deploy.js
- test/atm/ATMLiquidityMiningCalculateAccruedTLRTest.js
- test/atm/ATMLiquidityMiningStakeTest.js
- test/atm/ATMLiquidityMiningUnStakeTest.js
- test/atm/ATMLiquidityMiningWithdrawTLRTest.js
- test/base/LendingPoolDepositTest.js
- test/base/LendingPoolWithdrawTest.js
It includes:
- The Settings contract as a reference in the TTokens.
- Changes in the unit tests.
> [PROTOCOL-346] Add Settings in TTokens

- contracts/util/LoanLib.sol
- test/base/EtherCollateralLoansTakeOutLoanTest.js
- test/base/LoansBaseCanLoanGoToEOATest.js
- test/base/LoansBaseTakeOutLoanTest.js
It:
* Removes `CollateralBuffer` and `LiquidateEthPrice`values from the loan to EOA check
> [PROTOCOL-400] Fix minimum collateral buffer for loan to EOA

- contracts/base/LoansBase.sol
- test/base/EtherCollateralLoansTakeOutLoanTest.js
- test/base/LoansBaseTakeOutLoanTest.js
It is:
- Added supply-to-debt check at the takeOutLoan() function
> [PROTOCOL-430] - Add Supply-to-Debt Validation Modifier to takeOutLoan()

- contracts/mock/base/EtherCollateralLoansMock.sol
- contracts/mock/base/LoansBaseMock.sol
- contracts/mock/base/TokenCollateralLoansMock.sol
- contracts/util/LoanLib.sol
- test/base/EtherCollateralLoansGetCollateralInfoTest.js
- test/base/EtherCollateralLoansTakeOutLoanTest.js
- test/base/LoansBaseTakeOutLoanTest.js
- test/utils/consts.js
It:
* Calculates the interest rate for the loan duration based off the loan terms APR interest rate.
> Calculate loan interest rate for loan duration.

- contracts/base/LogicVersionsRegistry.sol
- contracts/interfaces/LogicVersionsRegistryInterface.sol
- contracts/util/LogicVersionLib.sol
It includes:
- Changes to support multiple versions for a logic version.
- Delete the remove function (comment in PR).
> [PROTOCOL-414] [L03] Support Multiple Versions for a Logic Address

- .editorconfig
- .prettierrc
- package.json
- yarn.lock
Works for .sol, .js, .ts, .md, .json
> Update tooling to support linting and re-adding committed files

- contracts/providers/chainlink/ChainlinkAggregator.sol
- test/providers/chainlink/ChainlinkAggregatorValueForTest.js
It is:
- Added methods in ChainlinkAggregator to support additional tokens with a bridge token
> Updating chainlink aggregator to support multiple routes

- contracts/base/LendingPool.sol
- Fixing method call for : 
-- https://github.com/teller-protocol/teller-protocol-v1/blob/develop/contracts/base/LendingPool.sol#L253
-- https://github.com/teller-protocol/teller-protocol-v1/blob/develop/contracts/base/LendingPool.sol#L262
> Fixing calculateCurrentLenderInterestEarned method call

- tasks/get-market.ts
- test/assetSettings.test.ts
- test/settings.test.ts
It: 
* Createss custom snapshots for each test setup for much faster deployments.
> Custom unit testing snapshots

- deploy/1_logic_contracts.ts
- deploy/2_initialize_settings.ts
- hardhat.config.ts
- utils/deploy-helpers.ts
- utils/get-funds.ts
- utils/swapTokens.ts
It is:
-  a JS helper to be used during testing to be able to buy tokens to deposit into the LP
> [PROTOCOL-467] Create Swapper helper

- test/fixtures/index.ts
- test/fixtures/loans.ts
- test/fixtures/markets.ts
- test/integration/loans.test.ts
- utils/hre-extensions.ts
It is:
- Adding loans fixture for integration tests
> Test fixture - loans

- hardhat.config.ts
- test/fixtures/loans.ts
- test/integration/loans.test.ts
- utils/hre-extensions.ts
- utils/mock-cra-response.ts
Contains the following loan integration scenarios: 
- Creating a loan with terms, depositing collateral and taking out a loan successfully
- Creating a loan with terms and try to take out a loan without collateral unsuccessfully
- Taking out and repaying a loan successfully
- Taking out a loan unsuccessfully with invalid debt ratio
> [PROTOCOL-474] Loans integration tests

- test/integration/settings.test.ts
- utils/hre-extensions.ts
Includes integration tests for the following scenarios
- Pause the platform and try to take out a loan
- Updating platform settings and try to take out a loan
- Add signers as a pauser and as not a pauser
> [PROTOCOL-473] Settings integration tests

- contracts/base/Loans.sol
- test/integration/loans.test.ts
It is:
- Adding conditional to allow collateral withdrawal after creation of a loan and before taking it out
- Loans test scenario
> Fix - Withdraw collateral

- test/integration/lending-pool.test.ts
- utils/hre-extensions.ts
It is:
- Update hre bn extension
- Lending pool integration test
> [PROTOCOL-475] Lending pool integration tests

- contracts/base/Loans.sol
- test/integration/loans.test.ts
It is:
- Adding  scenario for partial collateral withdrawal
> Loans integration test - partial withdrawal

- contracts/providers/chainlink/ChainlinkAggregator.sol
- contracts/util/LoanLib.sol
It is:
Using SignedSafeMath library for:
- LoanLib.sol - getCollateralNeededInfo method
- ChainlinkAggregator.sol - _valueFor and _priceFor internal methods
> [PROTOCOL-452] [M06] Unsafe arithmetic operations

- contracts/base/Escrow.sol
It is:
- Updated check on Escrow contract creation to mitigate dust attacks
> [PROTOCOL-446] [H01] Denial of service attack on new escrows

- contracts/base/BaseEscrowDapp.sol
- contracts/base/EscrowFactory.sol
- contracts/util/AddressArrayLib.sol
It is:
- Added check within the add method from the AddressArrayLib library to check if the newItem address already exists in the self address array
> [PROTOCOL-454] [L01] Duplicated values could be added into lists

- deploy/1_settings.ts
- deploy/7_create_markets.ts
- package.json
- utils/deploy-helpers.ts
- utils/hre-extensions.ts
- yarn.lock
It saves all the deployed contract addresses for each network in a single file in a clean and organized structure. 
Example: 
```json
{
"lendingPools": {
"DAI": "0xEE3F7e803Db86d3ae90074e2Af3AA0c33550A096"
},
"libraries": {
"LoanLib": "0x3070A39E8A770b5D364FA6a9d9289334Cf409c27"
},
"logics": {
"AssetSettings": "0x0cb9C355d4532818C9c15aCeB688c57F6680b2C0",
"ChainlinkAggregator": "0xB85c70A0d2D83F5a76503FfB1962C72d9A3F6561",
"Compound": "0xDfbC2891b0F7c0431AB9a07C024BE16D9c79E00e",
"EscrowFactory": "0xBa50038fC0Bd3131B7a8919e40D53D3778dacB15",
"EtherCollateralLoans": "0xCA362f343560F2421f71c0D246DcB1dc33aFd2A1",
"LendingPool": "0xc646556A06b52A2cA24aa8e59A50e6D93b8B1926",
"LoanTermsConsensus": "0xF800A1ad45D81757D3B2D16aae5D5BD0933AE405",
"MarketFactory": …
```
> Update saving deployment addreses

- contracts/base/LogicVersionsRegistry.sol
Adds the forgotten function to change the LogicVersionRegistry ownership.
> Change LVR Ownership

- .github/workflows/develop-push.yml
- .github/workflows/run-ci.yml
- hardhat.config.ts
- package.json
- test/gas-estimator.ts
- tsconfig.json
- utils/gas-estimator.ts
- yarn.lock
On push to develop (merged), we run the test suite and the gas estimator util then save their output in the gas/ folder. The gas folder is organized by commit SHA.
[Sample action](https://github.com/teller-protocol/teller-protocol-v1/actions/runs/681304565) 
[Output location](https://github.com/teller-protocol/teller-protocol-v1/tree/gas-estimates/gas)
Closes #330
> [PROTOCOL 484-490] Estimate Gas

- tasks/test.ts
- test/helpers/story/drivers/dapp-story-test-driver.ts
- test/helpers/story/drivers/lending-pool-story-test-driver.ts
- test/helpers/story/drivers/loan-story-test-driver.ts
- test/helpers/story/drivers/story-test-driver.ts
- test/helpers/story/generator/story-generator.ts
- test/helpers/story/story-helpers.ts
- test/integration/story-test-manager.ts
Breaks out each testing domain into a separate Mocha Suite for better console rendering
> Feature/story test/domain suite tests

- deploy/protocol.ts
> Fix Deploy Output Indentation 

- contracts/lending/ttoken/strategies/compound/TTokenCompoundStrategy_1.sol
Flips the calculation to subtract last to avoid unnecessary overflow errors.
> [PROTOCOL-632] [C02] Redeem Calculation Overflow

- contracts/lending/ttoken/TToken_V1.sol
- contracts/lending/ttoken/TToken_V2.sol
- deploy/protocol.ts
Pass the `TToken` strategy the full amount of funds needed to be available
> [PROTOCOL-629] [C01] Funding strategy mismatch

- contracts/lending/ttoken/strategies/compound/TTokenCompoundStrategy_1.sol
When targeting a balance to withdraw from Compound, only target the `medianRatio` instead of the difference from the `storedRatio` to correctly rebalance the amount of available funds.
> [PROTOCOL-633] [C03] Incorrect Rebalancing Calculation

- contracts/lending/ttoken/TToken_V1.sol
- contracts/lending/ttoken/data.sol
removed redundant and unused `ONE_HUNDRED_PERCENT` constant definition
> [PROTOCOL-647] [N03] Unused Constant

- contracts/lending/ttoken/strategies/compound/TTokenCompoundStrategy_1.sol
explicitly validates the consistency of upper and lower limits for the desired asset ratio.
> [PROTOCOL-638] [L02] Missing validation

- contracts/lending/ttoken/TToken_V1.sol
Document requirements in TToken underlying address configuration
>  [PROTOCOL-641] [L04] ERC20 optional parameters

- contracts/market/CreateLoanFacet.sol
- contracts/market/ProviderFactoryFacet.sol
- contracts/market/cra/DataProvider.sol
- contracts/market/cra/ProcessRequestLib.sol
- contracts/market/cra/market-handler/MarketHandler.sol
- contracts/market/cra/market-handler/TellerMarketHandler.sol
- contracts/market/libraries/MarketLib.sol
- contracts/storage/market.sol
- hardhat.config.ts
- test/helpers/loans.ts
- test/integration/loans.test.ts
Test creation of new markets and providers by way of contracts and external libraries.
User can pull out loan using snark data
> test-flow pull request

- contracts/lending/ttoken/strategies/aave/TTokenAaveStrategy_1.sol
Some fixes implemented in the Compound strategy needed to be copied over to the Aave one.
> [PROTOCOL-687] Aave TToken Strategy OZ fixes

- config/asset-settings.ts
- config/chainlink.ts
- config/markets.ts
- config/nft.ts
- config/tokens.ts
It is:
- Enabled USDT market for Polygon
> [PROTOCOL-686] Use USDT instead of DAI for Polygon

- bugBounty.md
It is:
- Added bug bounty md file
> Bug bounty program

- package.json
enforce global use of node v14
> [PROTOCOL-858] Enforce Use of Node v14

- tasks/settings/update-asset-settings.ts
* Fixes the update asset setting task to compare the string values
> Fix asset setting task value comparison

- contracts/market/SignersFacet.sol
- contracts/price-aggregator/PriceAggregator.sol
- contracts/price-aggregator/pricers/ChainlinkPricer.sol
- deploy/price-agg.ts
- test/unit/pair-aggregator.test.ts
- test/unit/signers.test.ts
Updates SignersFacet and PriceAggregator to add authorization checks
> Authorization Fix to SignersFacet and PriceAggregator
